### ISSUE TITLE
concurrency of 1, does it guarantee order?

### ISSUE THREAD

**Issue by ORESoftware** [timdp/es6-promise-pool#2]
I haven't uses this lib before but considering it - one question I have is - given a concurrency of 1, and I pass multiple promises to the pool, does this lib guarantee the order of which they get run? In other words, they should run in series, but I want to make sure if A is passed before B, that A will always complete before B starts executing. Thanks!

**Comment by timdp** [comment]
Yep. It uses iterators underneath, and those are always sequential.

**Comment by ORESoftware** [comment]
Sounds good thanks
