### ISSUE TITLE
No argument passed to then function?

### ISSUE THREAD

**Issue by lxiaokun** [timdp/es6-promise-pool#7]
pool.start().then(function(data) {
     console.log(data);   // data is undefined, which is inconsistent with Promise API
})

**Comment by timdp** [comment]
I think it's perfectly valid to fulfil a promise with `undefined`. Otherwise, `async noop () {}` would be invalid too. Do you have a reference to the ECMAScript spec or another document that states that the result of a promise cannot be `undefined`?
